### ISSUE TITLE
npm ERR! not ok code 0

### ISSUE THREAD

**Issue by zqzhang** [siovene/cordova-plugin-oic-demo#1]
https://github.com/siovene/cordova-plugin-oic-demo#how-to-build has these commands, and I tried them on Ubuntu 14.04 host:

``` sh
sudo npm -g cordova grunt-cli
```

Which misses `install`: `sudo npm install -g cordova grunt-cli`.

``` sh
npm install
```

The local npm packages installation returns "npm ERR! not ok code 0", even with several tries using `npm cache clean` suggested by https://alicoding.com/how-to-fix-error-enoent-lstat-npm-when-trying-to-install-modules/ and https://github.com/npm/npm/issues/3664.

Some error messages for your reference.

``` text
npm http GET http://registry.npmjs.org/bytes/-/bytes-2.3.0.tgz

Error making request.
Error: tunneling socket could not be established, cause=connect EHOSTUNREACH
    at ClientRequest.onError (/home/zqzhang/work/cordova-plugin-oic-demo/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/node_modules/request/node_modules/tunnel-agent/index.js:176:17)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)

Please report this full log at https://github.com/Medium/phantomjs
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 1
```

``` text
npm http 200 http://registry.npmjs.org/promzard/-/promzard-0.3.0.tgz
npm ERR! EEXIST, mkdir '/home/zqzhang/work/cordova-plugin-oic-demo/node_modules/grunt-contrib-connect/node_modules/connect/node_modules/csurf/node_modules/csrf/node_modules/uid-safe/node_modules/random-bytes'
File exists: /home/zqzhang/work/cordova-plugin-oic-demo/node_modules/grunt-contrib-connect/node_modules/connect/node_modules/csurf/node_modules/csrf/node_modules/uid-safe/node_modules/random-bytes
Move it away, and try again. 

npm ERR! System Linux 3.13.0-62-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/zqzhang/work/cordova-plugin-oic-demo
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/zqzhang/work/cordova-plugin-oic-demo/node_modules/grunt-contrib-connect/node_modules/connect/node_modules/csurf/node_modules/csrf/node_modules/uid-safe/node_modules/random-bytes
npm ERR! fstream_path /home/zqzhang/work/cordova-plugin-oic-demo/node_modules/grunt-contrib-connect/node_modules/connect/node_modules/csurf/node_modules/csrf/node_modules/uid-safe/node_modules/random-bytes/index.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/lib/nodejs/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/home/zqzhang/tmp/npm-9240-Jglu3ugm/1458092398951-0.963618224253878/package/lib/zlib/inflate.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-62-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/zqzhang/work/cordova-plugin-oic-demo
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/zqzhang/tmp/npm-9240-Jglu3ugm/1458092398951-0.963618224253878/package/lib/zlib/inflate.js
npm ERR! fstream_path /home/zqzhang/tmp/npm-9240-Jglu3ugm/1458092398951-0.963618224253878/package/lib/zlib/inflate.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 200 http://registry.npmjs.org/brace-expansion
npm http 200 http://registry.npmjs.org/read/-/read-1.0.7.tgz
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/home/zqzhang/work/cordova-plugin-oic-demo/node_modules/cordova/node_modules/cordova-lib/node_modules'
npm ERR! error rolling back  cordova-lib@6.0.0 { [Error: ENOTEMPTY, rmdir '/home/zqzhang/work/cordova-plugin-oic-demo/node_modules/cordova/node_modules/cordova-lib/node_modules']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/home/zqzhang/work/cordova-plugin-oic-demo/node_modules/cordova/node_modules/cordova-lib/node_modules' }
npm http 200 http://registry.npmjs.org/uid-number/-/uid-number-0.0.5.tgz
npm http 200 http://registry.npmjs.org/validate-npm-package-name/-/validate-npm-package-name-2.2.2.tgz
npm ERR! Error: ENOENT, lstat '/home/zqzhang/work/cordova-plugin-oic-demo/node_modules/grunt-contrib-htmlmin/node_modules/html-minifier/node_modules/cli/node_modules/glob/node_modules/minimatch/minimatch.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-62-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/zqzhang/work/cordova-plugin-oic-demo
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/zqzhang/work/cordova-plugin-oic-demo/node_modules/grunt-contrib-htmlmin/node_modules/html-minifier/node_modules/cli/node_modules/glob/node_modules/minimatch/minimatch.js
npm ERR! fstream_path /home/zqzhang/work/cordova-plugin-oic-demo/node_modules/grunt-contrib-htmlmin/node_modules/html-minifier/node_modules/cli/node_modules/glob/node_modules/minimatch/minimatch.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/home/zqzhang/work/cordova-plugin-oic-demo/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/node_modules/nan/LICENSE'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-62-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/zqzhang/work/cordova-plugin-oic-demo
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/zqzhang/work/cordova-plugin-oic-demo/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/node_modules/nan/LICENSE
npm ERR! fstream_path /home/zqzhang/work/cordova-plugin-oic-demo/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/node_modules/nan/LICENSE
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 200 http://registry.npmjs.org/node-uuid/-/node-uuid-1.3.3.tgz
npm http 200 http://registry.npmjs.org/pegjs/-/pegjs-0.6.2.tgz
npm http 200 http://registry.npmjs.org/hawk/-/hawk-1.1.1.tgz
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/home/zqzhang/work/cordova-plugin-oic-demo/node_modules/cordova/node_modules/cordova-lib/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion'
npm ERR! error rolling back  cordova@6.0.0 { [Error: ENOTEMPTY, rmdir '/home/zqzhang/work/cordova-plugin-oic-demo/node_modules/cordova/node_modules/cordova-lib/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/home/zqzhang/work/cordova-plugin-oic-demo/node_modules/cordova/node_modules/cordova-lib/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion' }
```

**Comment by zqzhang** [comment]
http://stackoverflow.com/questions/33162560/error-tunneling-socket-could-not-be-established-cause-connect-econnrefused-10 helps me resolve this issue, because I am behind a proxy.

``` sh
npm config set proxy http://proxyhostname:proxyport
npm config set https-proxy http://proxyhostname:proxyport
```

Also try disable ssl and set registry to http instead of https:

``` sh
npm config set registry=http://registry.npmjs.org/
npm config set strict-ssl false
```

See also
- https://github.com/npm/npm/issues/2472
- https://github.com/Medium/phantomjs#installation-fails-with-error-read-econnreset-or-error-connect-etimedout

**Comment by zqzhang** [comment]
By the way, what I missed is the https-proxy only because I have set all other three.

``` sh
npm config set https-proxy http://proxyhostname:proxyport
```
