### ISSUE TITLE
`grunt run:android` failed

### ISSUE THREAD

**Issue by zqzhang** [siovene/cordova-plugin-oic-demo#4]
Seems this is also an issue of proxy. See the complete log of running `grunt run:android`:

``` text
~/work/cordova-plugin-oic-demo$ grunt run:android
Running "run:android" (run) task

Running "clean" task
ANDROID_HOME=/home/zqzhang/work/crosswalk-src/src/third_party/android_tools/sdk

JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64

Downloading http://services.gradle.org/distributions/gradle-2.2.1-all.zip



>> Exception in thread "main"
>> java.lang.RuntimeException: java.net.ConnectException: Connection timed out
>> at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
>>  at org.gradle.wrapper.Install.createDist(Install.java:47)
>> at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
>>  at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
>> Caused by: java.net.ConnectException: Connection timed out
>> at java.net.PlainSocketImpl.socketConnect(Native Method)
>>  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
>>  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
>> at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
>>  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
>>  at java.net.Socket.connect(Socket.java:579)
>>  at java.net.Socket.connect(Socket.java:528)
>>  at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
>> at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
>>  at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
>>  at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
>>  at sun.net.www.http.HttpClient.New(HttpClient.java:308)
>>  at sun.net.www.http.HttpClient.New(HttpClient.java:326)
>>  at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:997)
>>  at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933)
>>  at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:851)
>>  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301)
>>  at org.gradle.wrapper.Download.downloadInternal(Download.java:59)
>>  at org.gradle.wrapper.Download.download(Download.java:45)
>> at org.gradle.wrapper.Install$1.call(Install.java:60)
>>  at org.gradle.wrapper.Install$1.call(Install.java:47)
>>  at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
>>  ... 3 more
>> 
>> Error: /home/zqzhang/work/cordova-plugin-oic-demo/platforms/android/gradlew: Command failed with exit code 1
Warning: Task "clean" failed. Use --force to continue.

Aborted due to warnings.


Execution Time (2016-03-21 07:57:40 UTC)
clean          2m 8.5s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 2m 8.5s
```

**Comment by zqzhang** [comment]
Not sure if it is OK to use `grunt-proxy` module at

https://www.npmjs.com/package/grunt-proxy

**Comment by zqzhang** [comment]
Or can we download http://services.gradle.org/distributions/gradle-2.2.1-all.zip manually and use it from local file system?

**Comment by siovene** [comment]
Sounds like proxy issues again, not really an issue on this project. 

Create a file called `gradle.properties` in `platform/android`, with the following content:

```
systemProp.http.proxyHost=www.somehost.org
systemProp.http.proxyPort=8080
systemProp.http.proxyUser=userid
systemProp.http.proxyPassword=password
systemProp.http.nonProxyHosts=*.nonproxyrepos.com|localhost  

systemProp.https.proxyHost=www.somehost.org
systemProp.https.proxyPort=8080
systemProp.https.proxyUser=userid
systemProp.https.proxyPassword=password
systemProp.https.nonProxyHosts=*.nonproxyrepos.com|localhost
```

(customize to your heart's content)
